spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pweb?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    database: mysql
  messages:
    basename: messages/messages
  flyway:
    locations: classpath:/db/migration/comum